### ISSUE TITLE
_load_icon picks wrong resolution

### ISSUE THREAD

**Issue by loehnertj** [Infinidat/infi.systray#29]
The ``_load_icon`` function specifies ``LR_DEFAULTSIZE`` flag, which gives 32x32 if available. This is particularly noticeable if an .ico file contains different images for different resolutions. 

Instead it should use ``GetSystemMetrics(SM_CXSMICON)`` / ``GetSystemMetrics(SM_CYSICON)`` to get the right size for the system. Code can be copy-pasted from ``_prep_menu_icon`` function which already does this.

**Comment by wiggin15** [comment]
Hi. A PR to fix this for this will be welcome :)
