### ISSUE TITLE
Icon not loading at windows start

### ISSUE THREAD

**Issue by marcelomanzo** [Infinidat/infi.systray#33]
Hello,

I have packaged my app with the SysTrayIcon, everything works exceptionally well except the icon.
Please note that I'm using pyinstaller to ship my app as an exe 

When the app starts with the windows startup the icon is not loaded properly:
![image](https://user-images.githubusercontent.com/12878783/99435034-905f9a00-28dd-11eb-9c7a-d4b2bdfaec9a.png)

If I close the app, and open it again, it loads the icon properly, so it's very specific for windows startup.

Any suggestion how and what to debug?

![image](https://user-images.githubusercontent.com/12878783/99434987-8047ba80-28dd-11eb-8be2-b6b715a29ca5.png)

**Comment by MarkimGarito** [comment]
It is probably the way you declare the path to the image. Use the absolute path of the image

**Comment by marcelo-srs** [comment]
You are right, you can close this.
