### ISSUE TITLE
systray.shutdown with tkinter doesn't work together 

### ISSUE THREAD

**Issue by mustafa-ozlu** [Infinidat/infi.systray#47]
i wrote a ntp time server gui.
and add a systray icon. when i click on systray icon quit, quit to icon but running main program.
if i hide the window and click on quit program running background.
how can i solve this problem.
[ntpserver.txt](https://github.com/Infinidat/infi.systray/files/9010618/ntpserver.txt)

**Comment by wallace09** [comment]
solved by pystray library

**Comment by mustafa-ozlu** [comment]
solved with pystray library
