### ISSUE TITLE
How to use default Quit option to quit my application instead of quitting only infi.systray?

### ISSUE THREAD

**Issue by siddheshgunjal** [Infinidat/infi.systray#50]
Right now I have Python application running in background. When I Click on default Quit option it only closes the infi.systray icon but my application keeps running in background. I have also made my own function to quit the entire application and clear the memory and I can create a new option to run that function, but then there will be 2 quit buttons in the options i which is not acceptable.

I have 2 options to proceed with:

1. Use my own function after removing default Quit button from menu_options.
2. Map my own function on default Quit button somehow.

Any help in achieving either of these 2 will be helpful.

**Comment by wiggin15** [comment]
Sounds like you're looking for `on_quit`, which maps a function to call when "Quit" is clicked.
From the README:
>
>A "Quit" command is always appended to the end of the icon context menu, after the menu options specified by the user. To perform operations when Quit is selected, pass "on_quit=callback" as a parameter, e.g.:
> ```
> def on_quit_callback(systray):
>     program.shutdown()
> systray = SysTrayIcon("icon.ico", "Example tray icon", menu_options, on_quit=on_quit_callback)```

**Comment by siddheshgunjal** [comment]
Worked! Thank you very much!
