### ISSUE TITLE
How to install on windows?

### ISSUE THREAD

**Issue by aaryavrate** [Infinidat/infi.systray#7]
Is it compatible with windows? How to install on win 8?

**Comment by wiggin15** [comment]
Yes, the package is intended for use on Windows.
You can install this package from PyPI using `pip` or `easy_install` (preferred method) or clone the repository and run `python setup.py install`. See the documentation about Python packages: https://packaging.python.org/tutorials/installing-packages/

**Comment by craftpip** [comment]
please add the pip install command in your readme, will be great to quickly install it

**Comment by wiggin15** [comment]
Done. Thanks.
